# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/dokumenty/fpga/gpu/gpu.srcs/sources_1/bd/MainDesign/ip/MainDesign_xbar_3/MainDesign_xbar_3.xci
# IP: The module: 'MainDesign_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/dokumenty/fpga/gpu/gpu.gen/sources_1/bd/MainDesign/ip/MainDesign_xbar_3/MainDesign_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MainDesign_xbar_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/dokumenty/fpga/gpu/gpu.srcs/sources_1/bd/MainDesign/ip/MainDesign_xbar_3/MainDesign_xbar_3.xci
# IP: The module: 'MainDesign_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/dokumenty/fpga/gpu/gpu.gen/sources_1/bd/MainDesign/ip/MainDesign_xbar_3/MainDesign_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MainDesign_xbar_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
