# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/dokumenty/fpga/pynq_test/pynq_test.srcs/sources_1/bd/MainDesign/ip/MainDesign_HDMI_OUT_0_0/MainDesign_HDMI_OUT_0_0.xci
# IP: The module: 'MainDesign_HDMI_OUT_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: F:/dokumenty/fpga/pynq_test/pynq_test.srcs/sources_1/ip/selectio_wiz_1/selectio_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==selectio_wiz_1 || ORIG_REF_NAME==selectio_wiz_1} -quiet] -quiet

# IP: F:/dokumenty/fpga/pynq_test/pynq_test.srcs/sources_1/bd/MainDesign/ip/MainDesign_HDMI_OUT_0_0/MainDesign_HDMI_OUT_0_0.xci
# IP: The module: 'MainDesign_HDMI_OUT_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: F:/dokumenty/fpga/pynq_test/pynq_test.srcs/sources_1/ip/selectio_wiz_1/selectio_wiz_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==selectio_wiz_1 || ORIG_REF_NAME==selectio_wiz_1} -quiet] -quiet
