# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/dokumenty/fpga/pynq_test/pynq_test.srcs/sources_1/bd/MainDesign/ip/MainDesign_processing_system7_0_0/MainDesign_processing_system7_0_0.xci
# IP: The module: 'MainDesign_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/dokumenty/fpga/pynq_test/pynq_test.gen/sources_1/bd/MainDesign/ip/MainDesign_processing_system7_0_0/MainDesign_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MainDesign_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/dokumenty/fpga/pynq_test/pynq_test.srcs/sources_1/bd/MainDesign/ip/MainDesign_processing_system7_0_0/MainDesign_processing_system7_0_0.xci
# IP: The module: 'MainDesign_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/dokumenty/fpga/pynq_test/pynq_test.gen/sources_1/bd/MainDesign/ip/MainDesign_processing_system7_0_0/MainDesign_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MainDesign_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
