# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/dokumenty/fpga/pynq_test/pynq_test.srcs/sources_1/ip/selectio_wiz_1/selectio_wiz_1.xci
# IP: The module: 'selectio_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/dokumenty/fpga/pynq_test/pynq_test.gen/sources_1/ip/selectio_wiz_1/selectio_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'selectio_wiz_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/dokumenty/fpga/pynq_test/pynq_test.gen/sources_1/ip/selectio_wiz_1/selectio_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'selectio_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/dokumenty/fpga/pynq_test/pynq_test.srcs/sources_1/ip/selectio_wiz_1/selectio_wiz_1.xci
# IP: The module: 'selectio_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/dokumenty/fpga/pynq_test/pynq_test.gen/sources_1/ip/selectio_wiz_1/selectio_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'selectio_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/dokumenty/fpga/pynq_test/pynq_test.gen/sources_1/ip/selectio_wiz_1/selectio_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'selectio_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
